"""Add check constraints

Revision ID: 19ed412ee6e4
Revises: fad7289030d4
Create Date: 2026-08-31 22:36:48.595496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ed412ee6e4'
down_revision: Union[str, Sequence[str], None] = 'fad7289030d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_check_constraint('chk_calculated_score_range', 'calculated_score >= 0 AND calculated_score <= 100')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint('chk_calculated_score_range', type_='check')
    # ### end Alembic commands ###
