"""phase2_audit_and_submission_overrides

Revision ID: 73ba237b9a1e
Revises: 19ed412ee6e4
Create Date: 2026-08-31 23:06:08.611504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '73ba237b9a1e'
down_revision: Union[str, Sequence[str], None] = '19ed412ee6e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='User who performed the action'),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('automatic_score', sa.Float(), nullable=True, comment='Auto-calculated score (0-100) generated by the system'))
        batch_op.add_column(sa.Column('final_score', sa.Float(), nullable=True, comment='Final score (0-100), either automatic or teacher-overridden'))
        batch_op.add_column(sa.Column('graded_by_id', sa.Integer(), nullable=True, comment='Teacher who finalized the grade (if applicable)'))
        batch_op.add_column(sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the teacher finalized the grade'))
        batch_op.create_foreign_key('fk_submission_graded_by', 'users', ['graded_by_id'], ['id'], ondelete='SET NULL')
        
        # SQLite doesn't support named check constraint dropping in batch mode sometimes if it was not created in the metadata properly,
        # but batch_op handles recreating the table. We drop the old one and add the new ones.
        # Wait, the previous migration added 'chk_calculated_score_range'. We drop it.
        # SQLite batch mode requires the constraint name exactly as it was.
        # We will suppress the drop_constraint for SQLite if it fails, or just use naming convention.
        # Alembic usually handles this, but since we are replacing calculated_score, the new check constraints will be in the recreated table.
        # It's safest to just let batch_op do it.
        batch_op.drop_constraint('chk_calculated_score_range', type_='check')
        batch_op.create_check_constraint('chk_automatic_score_range', 'automatic_score >= 0 AND automatic_score <= 100')
        batch_op.create_check_constraint('chk_final_score_range', 'final_score >= 0 AND final_score <= 100')
        batch_op.drop_column('calculated_score')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculated_score', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint('chk_final_score_range', type_='check')
        batch_op.drop_constraint('chk_automatic_score_range', type_='check')
        batch_op.create_check_constraint('chk_calculated_score_range', 'calculated_score >= 0 AND calculated_score <= 100')
        batch_op.drop_constraint('fk_submission_graded_by', type_='foreignkey')
        batch_op.drop_column('graded_at')
        batch_op.drop_column('graded_by_id')
        batch_op.drop_column('final_score')
        batch_op.drop_column('automatic_score')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
