"""Add messages table

Revision ID: 76cef7cc29c8
Revises: b1c2d3e4f5a6
Create Date: 2026-09-29 11:35:12.708789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cef7cc29c8'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)

    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.alter_column('simulation_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('ohms_law', 'titration', 'velocity', 'ph', 'food_tests', 'separation', 'moments', 'enzyme_activity', 'l6_titration', 'internal_resistance', 'u6_photosynthesis', 'u6_kinetics', 'u6_young_modulus', 'generic', name='simulation_type_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'generic'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.alter_column('simulation_type',
               existing_type=sa.Enum('ohms_law', 'titration', 'velocity', 'ph', 'food_tests', 'separation', 'moments', 'enzyme_activity', 'l6_titration', 'internal_resistance', 'u6_photosynthesis', 'u6_kinetics', 'u6_young_modulus', 'generic', name='simulation_type_enum'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False,
               existing_server_default=sa.text("'generic'"))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_id'))

    op.drop_table('messages')
    # ### end Alembic commands ###
